version: '3.7'

services:

  app:
    container_name: app
    restart: always
    volumes:
      - ./:/var/www/app
    build:
      dockerfile: ./docker/python/Dockerfile
      context: .
    command: flask run --host=0.0.0.0 --port=5000
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development

  postgres:
    container_name: postgres
    restart: always
    image: postgres:12-alpine
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
      - ./docker/postgres/config/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres